# Generated by Django 5.2.7 on 2026-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
