# Generated by Django 5.2.7 on 2026-03-27 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employee_profiles/photos/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('personal_phone', models.CharField(max_length=25)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=25)),
                ('current_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('cnic', models.CharField(max_length=50, unique=True, verbose_name='CNIC / National ID')),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=20)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Onboarding', 'Onboarding'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('joining_date', models.DateField()),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('work_location', models.CharField(blank=True, max_length=120)),
                ('shift', models.CharField(max_length=80)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Bank', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_title', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Approver', 'Approver'), ('Super Admin', 'Super Admin')], default='Employee', max_length=20)),
                ('cnic_copy', models.FileField(blank=True, null=True, upload_to='employee_profiles/documents/cnic/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_profiles/documents/resumes/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='employee_profiles/documents/offer_letters/')),
                ('contract', models.FileField(blank=True, null=True, upload_to='employee_profiles/documents/contracts/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_profiles', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='accounts.employeeprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee registration',
                'verbose_name_plural': 'Employee registrations',
                'ordering': ['full_name', 'employee_code'],
                'permissions': [('can_manage_team', 'Can manage team records'), ('can_approve_employee_records', 'Can approve employee records'), ('can_view_employee_directory', 'Can view employee directory')],
            },
        ),
    ]
