# Generated by Django 5.2.7 on 2026-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Probation', 'Probation'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=20),
        ),
    ]
