# Generated by Django 5.2.7 on 2026-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='scheduled_checkin',
            field=models.TimeField(blank=True, help_text='Expected daily check-in time for late-arrival detection.', null=True, verbose_name='Scheduled Check-in'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='scheduled_checkout',
            field=models.TimeField(blank=True, help_text='Expected daily check-out time for early-departure detection.', null=True, verbose_name='Scheduled Check-out'),
        ),
    ]
