# Generated by Django 5.2.7 on 2026-05-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeprofile_shift_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='scheduled_checkin',
            field=models.TimeField(blank=True, help_text='Auto-filled from Shift. Override only when no shift is assigned.', null=True, verbose_name='Scheduled Check-in'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='scheduled_checkout',
            field=models.TimeField(blank=True, help_text='Auto-filled from Shift. Override only when no shift is assigned.', null=True, verbose_name='Scheduled Check-out'),
        ),
    ]
