# Generated by Django 5.2.7 on 2026-06-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_manager_approved_status_and_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='cnic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CNIC / National ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='payment_mode',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Transfer', 'Online Transfer'), ('Other', 'Other'), ('-', '-')], default='Bank', max_length=20),
        ),
    ]
