# Generated by Django 5.2.7 on 2026-04-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='code',
        ),
    ]
