# Generated by Django 5.2.7 on 2026-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leavetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='available_for_probation',
            field=models.BooleanField(default=False),
        ),
    ]
