# Generated by Django 5.2.7 on 2026-06-15 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_short_leave_period_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortleavepolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shortleavepolicy',
            name='max_per_month',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximum short leave requests per employee per calendar month.', verbose_name='Max short leaves per month'),
        ),
        migrations.AlterField(
            model_name='shortleavepolicy',
            name='min_hours_before_afternoon',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), help_text='Employee must have checked in and worked at least this many hours before applying.', max_digits=4, verbose_name='Min hours worked before afternoon short leave'),
        ),
        migrations.AlterField(
            model_name='shortleaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
