# Generated by Django 5.2.7 on 2026-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_alter_shortleavepolicy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_backdated',
            field=models.BooleanField(default=True, help_text='When enabled, employees can apply for this leave type on past dates. Disable for Annual/Planned Leave which must be requested in advance.', verbose_name='Allow backdated applications'),
        ),
    ]
