# Generated by Django 5.2.7 on 2026-04-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_employeeprofile_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Bank', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_title', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_setup', to='accounts.employeeprofile')),
            ],
            options={
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deduction_type', models.CharField(choices=[('Fixed', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Fixed', max_length=20)),
                ('deduction_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'min_salary'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_salary__isnull', True), ('max_salary__gte', models.F('min_salary')), _connector='OR'), name='salary_tax_slab_max_gte_min')],
            },
        ),
    ]
