# Generated by Django 5.2.7 on 2026-04-09 13:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeprofile_employment_type'),
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Locked', 'Locked')], default='Draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_addition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eobi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_statutory', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_title', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDeductionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('eobi_employee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provident_fund_employee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('provident_fund_employer_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('social_security_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_statutory_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='salarytaxslab',
            options={'ordering': ['-effective_from', 'sort_order', 'min_salary']},
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='effective_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='fiscal_year',
            field=models.CharField(default='2025-2026', help_text='Example: 2025-2026', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='salarytaxslab',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_tax_slab_effective_to_gte_from'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.employeeprofile'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='salary.payrollrun'),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrevision',
            name='salary_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='salary.salarysetup'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='salary.salaryrevision'),
        ),
        migrations.AddConstraint(
            model_name='statutorydeductionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='statutory_policy_effective_to_gte_from'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_payroll_run_year_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='payroll_run_month_1_12'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payslip_per_run_employee'),
        ),
    ]
