# Generated by Django 5.2.7 on 2026-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_payrollrun_payslip_salaryrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysetup',
            name='currency',
            field=models.CharField(default='PKR', max_length=10),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='general_balance_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='general_paid_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='general_total_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='ntn_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_balance_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_paid_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_permanent_loan_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_permanent_loan_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_refundable_loan_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_refundable_loan_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_starting_balance_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_starting_balance_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='pf_total_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarysetup',
            name='total_working_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
