# Generated by GitHub Copilot on 2026-04-16

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_salarysetup_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='paid_payslips',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
