# Generated by Django 5.2.7 on 2026-04-09 17:40

from datetime import date
from decimal import Decimal

from django.db import migrations, models


def seed_default_tax_slabs(apps, schema_editor):
    SalaryTaxSlab = apps.get_model("salary", "SalaryTaxSlab")
    SalaryTaxSlab.objects.all().delete()

    default_slabs = [
        ("Up to 600,000", Decimal("0"), Decimal("600000"), Decimal("0"), Decimal("0"), Decimal("0"), 1),
        ("600,000 to 1,200,000", Decimal("600000"), Decimal("1200000"), Decimal("600000"), Decimal("0"), Decimal("1"), 2),
        ("1,200,000 to 2,200,000", Decimal("1200000"), Decimal("2200000"), Decimal("1200000"), Decimal("6000"), Decimal("11"), 3),
        ("2,200,000 to 3,200,000", Decimal("2200000"), Decimal("3200000"), Decimal("2200000"), Decimal("116000"), Decimal("23"), 4),
        ("3,200,000 to 4,100,000", Decimal("3200000"), Decimal("4100000"), Decimal("3200000"), Decimal("345000"), Decimal("30"), 5),
        ("Above 4,100,000", Decimal("4100000"), None, Decimal("4100000"), Decimal("615000"), Decimal("35"), 6),
    ]

    for name, min_income, max_income, excess_over, base_tax, rate, order in default_slabs:
        SalaryTaxSlab.objects.create(
            name=name,
            fiscal_year="2025-2026",
            effective_from=date(2025, 7, 1),
            effective_to=None,
            annual_min_income=min_income,
            annual_max_income=max_income,
            taxable_excess_over=excess_over,
            base_tax=base_tax,
            rate_percent=rate,
            sort_order=order,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salarysetup_absent_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarytaxslab',
            options={'ordering': ['-effective_from', 'sort_order', 'annual_min_income']},
        ),
        migrations.RemoveConstraint(
            model_name='salarytaxslab',
            name='salary_tax_slab_max_gte_min',
        ),
        migrations.RemoveField(
            model_name='salarytaxslab',
            name='deduction_type',
        ),
        migrations.RemoveField(
            model_name='salarytaxslab',
            name='deduction_value',
        ),
        migrations.RemoveField(
            model_name='salarytaxslab',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='salarytaxslab',
            name='min_salary',
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='annual_max_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='annual_min_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='base_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='rate_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarytaxslab',
            name='taxable_excess_over',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='salarytaxslab',
            constraint=models.CheckConstraint(condition=models.Q(('annual_max_income__isnull', True), ('annual_max_income__gte', models.F('annual_min_income')), _connector='OR'), name='salary_tax_slab_annual_max_gte_min'),
        ),
        migrations.RunPython(seed_default_tax_slabs, migrations.RunPython.noop),
    ]
