# Generated by Django 5.2.7 on 2026-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_syncschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_buffer_minutes', models.PositiveIntegerField(default=0, help_text='Grace period after scheduled check-in. If an employee punches in more than this many minutes late, they are marked as Late.', verbose_name='Check-in Buffer (minutes)')),
                ('checkout_buffer_minutes', models.PositiveIntegerField(default=0, help_text='Early-leave allowance before scheduled check-out. If an employee punches out more than this many minutes early, they are marked as Early Checkout.', verbose_name='Check-out Buffer (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policy',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_early_checkout',
            field=models.BooleanField(default=False, verbose_name='Early Checkout'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Late Arrival'),
        ),
    ]
