# Generated by Django 5.2.7 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_devicesyncflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('work_from_home', 'Work From Home'), ('on_leave_paid', 'On Leave (Paid)'), ('on_leave_unpaid', 'On Leave (Unpaid)'), ('on_hourly_leave', 'On Hourly Leave'), ('public_holiday', 'Public Holiday'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
    ]
